# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/furkan/Desktop/Alan Algorithm"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/furkan/Desktop/Alan Algorithm"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/furkan/Desktop/Alan Algorithm/CMakeFiles" "/home/furkan/Desktop/Alan Algorithm/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/furkan/Desktop/Alan Algorithm/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pose

# Build rule for target.
pose: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pose
.PHONY : pose

# fast build rule for target.
pose/fast:
	$(MAKE) -f CMakeFiles/pose.dir/build.make CMakeFiles/pose.dir/build
.PHONY : pose/fast

#=============================================================================
# Target rules for targets named arduino-serial-lib

# Build rule for target.
arduino-serial-lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arduino-serial-lib
.PHONY : arduino-serial-lib

# fast build rule for target.
arduino-serial-lib/fast:
	$(MAKE) -f CMakeFiles/arduino-serial-lib.dir/build.make CMakeFiles/arduino-serial-lib.dir/build
.PHONY : arduino-serial-lib/fast

OnlyCode.o: OnlyCode.cpp.o

.PHONY : OnlyCode.o

# target to build an object file
OnlyCode.cpp.o:
	$(MAKE) -f CMakeFiles/pose.dir/build.make CMakeFiles/pose.dir/OnlyCode.cpp.o
.PHONY : OnlyCode.cpp.o

OnlyCode.i: OnlyCode.cpp.i

.PHONY : OnlyCode.i

# target to preprocess a source file
OnlyCode.cpp.i:
	$(MAKE) -f CMakeFiles/pose.dir/build.make CMakeFiles/pose.dir/OnlyCode.cpp.i
.PHONY : OnlyCode.cpp.i

OnlyCode.s: OnlyCode.cpp.s

.PHONY : OnlyCode.s

# target to generate assembly for a file
OnlyCode.cpp.s:
	$(MAKE) -f CMakeFiles/pose.dir/build.make CMakeFiles/pose.dir/OnlyCode.cpp.s
.PHONY : OnlyCode.cpp.s

arduino-serial-lib.o: arduino-serial-lib.c.o

.PHONY : arduino-serial-lib.o

# target to build an object file
arduino-serial-lib.c.o:
	$(MAKE) -f CMakeFiles/arduino-serial-lib.dir/build.make CMakeFiles/arduino-serial-lib.dir/arduino-serial-lib.c.o
.PHONY : arduino-serial-lib.c.o

arduino-serial-lib.i: arduino-serial-lib.c.i

.PHONY : arduino-serial-lib.i

# target to preprocess a source file
arduino-serial-lib.c.i:
	$(MAKE) -f CMakeFiles/arduino-serial-lib.dir/build.make CMakeFiles/arduino-serial-lib.dir/arduino-serial-lib.c.i
.PHONY : arduino-serial-lib.c.i

arduino-serial-lib.s: arduino-serial-lib.c.s

.PHONY : arduino-serial-lib.s

# target to generate assembly for a file
arduino-serial-lib.c.s:
	$(MAKE) -f CMakeFiles/arduino-serial-lib.dir/build.make CMakeFiles/arduino-serial-lib.dir/arduino-serial-lib.c.s
.PHONY : arduino-serial-lib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pose"
	@echo "... rebuild_cache"
	@echo "... arduino-serial-lib"
	@echo "... OnlyCode.o"
	@echo "... OnlyCode.i"
	@echo "... OnlyCode.s"
	@echo "... arduino-serial-lib.o"
	@echo "... arduino-serial-lib.i"
	@echo "... arduino-serial-lib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

